# Site wide configuration

title: Shrikrishna Singh
locale: en_US
description:
logo: site-logo.png
search: true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Shrikrishna Singh
  avatar: bio-photo.jpg
  email: krishnasingh.ss30@gmail.com
  disqus-shortname:
  twitter: sks444_
  facebook: #username
  github: sks444
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: sks444
  instagram: sks444_
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-99640829-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
